description: For multi-gpu experimentation

target:
        service: amlk8s
        name: itplabrr1cl1 
        vc: resrchvc

environment:
        image: orb_gen:latest
        registry: cvgroup.azurecr.io
        username: cvgroup 

code: 
    local_dir: $CONFIG_DIR/src

storage:
    data:
       storage_account_name: cvgroup
       container_name: datasets
       mount_dir: /mnt/data

jobs:
    - name: runner_last
      sku: G4
      #sku: G8
      command:
         #- python3 CLIP/setup.py develop
         - MKL_THREADING_LAYER=GNU python runner.py
