description: Default Protonets implementation from orbit repo

target:
        service: amlk8s
        name: itplabrr1cl1 
        vc: resrchvc

environment:
        image: base/job/pytorch/rocm4.5.2_ubuntu18.04_py3.8_pytorch_1.8.1:20220509T151538593  
        registry: singularitybase.azurecr.io
        #image: orb_gen:latest
        #registry: cvgroup.azurecr.io
        #username: cvgroup

code: 
    local_dir: $CONFIG_DIR/src

    #storage:
    #data:
    #   storage_account_name: dguill
    #   container_name: data
    #   mount_dir: /mnt/data
    #   #remote_dir: ORB_DATA
    #   #storage_id: dguill
    #   #local_dir: ../ORB_DATA

jobs:
    - name: simplet_test_1
      sku: G1 #@eastus2
      #sku: G8
      command:
         - MKL_THREADING_LAYER=GNU python3 test.py
